// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type PersonDto = {
    /**
     * The person's unique identifier
     */
    id: number;
    /**
     * The person's name
     */
    name?: {
        [key: string]: unknown;
    };
    /**
     * The person's profile image path
     */
    profile_path?: {
        [key: string]: unknown;
    };
    /**
     * The person's profile image URL
     */
    profile_url?: {
        [key: string]: unknown;
    };
    /**
     * The person's birthday
     */
    birthday?: {
        [key: string]: unknown;
    };
    /**
     * The person's deathday
     */
    deathday?: {
        [key: string]: unknown;
    };
    /**
     * The person's homepage URL
     */
    homepage?: {
        [key: string]: unknown;
    };
    /**
     * The person's imdb identifier
     */
    imdb_id?: {
        [key: string]: unknown;
    };
    /**
     * The person's kown for department
     */
    known_for_department?: {
        [key: string]: unknown;
    };
    /**
     * The person's place of birth
     */
    place_of_birth?: {
        [key: string]: unknown;
    };
    /**
     * The person's gender: 0 = Not specified, 1 = Female, 2 = Male, 3 = Non-binary
     */
    gender?: {
        [key: string]: unknown;
    };
    /**
     * The person's biography
     */
    biography?: {
        [key: string]: unknown;
    };
    /**
     * The person's popularity score
     */
    popularity?: {
        [key: string]: unknown;
    };
    /**
     * The person's slug
     */
    slug?: {
        [key: string]: unknown;
    };
    /**
     * The person's URL
     */
    url?: {
        [key: string]: unknown;
    };
};

export type GenreDto = {
    /**
     * The genre's ID
     */
    id: number;
    /**
     * The name of the genre
     */
    name: string;
};

export type MovieDto = {
    /**
     * The movie's unique identifier
     */
    id: number;
    /**
     * The title of the movie
     */
    title: {
        [key: string]: unknown;
    };
    /**
     * Poster path of the movie
     */
    poster_path?: {
        [key: string]: unknown;
    };
    /**
     * Poster URL of the movie
     */
    poster_url?: {
        [key: string]: unknown;
    };
    /**
     * Backdrop path of the movie
     */
    backdrop_path: {
        [key: string]: unknown;
    };
    /**
     * Backdrop URL of the movie
     */
    backdrop_url?: {
        [key: string]: unknown;
    };
    /**
     * Directors of the movie
     */
    directors: Array<PersonDto>;
    /**
     * Genres of the movie
     */
    genres: Array<GenreDto>;
    /**
     * Release date of the movie
     */
    release_date: {
        [key: string]: unknown;
    };
    /**
     * Overview of the movie
     */
    overview: {
        [key: string]: unknown;
    };
    /**
     * Budget of the movie in USD
     */
    budget: {
        [key: string]: unknown;
    };
    /**
     * Homepage URL of the movie
     */
    homepage: {
        [key: string]: unknown;
    };
    /**
     * Revenue of the movie in USD
     */
    revenue: {
        [key: string]: unknown;
    };
    /**
     * Runtime of the movie in minutes
     */
    runtime: {
        [key: string]: unknown;
    };
    /**
     * Original language of the movie
     */
    original_language: {
        [key: string]: unknown;
    };
    /**
     * Original title of the movie
     */
    original_title: {
        [key: string]: unknown;
    };
    /**
     * Status of the movie
     */
    status: {
        [key: string]: unknown;
    };
    /**
     * Popularity score of the movie
     */
    popularity: number;
    /**
     * Vote average of the movie
     */
    vote_average: number;
    /**
     * Vote count of the movie
     */
    vote_count: number;
    /**
     * Slug of the movie
     */
    slug?: {
        [key: string]: unknown;
    };
    /**
     * URL to the movie page
     */
    url?: {
        [key: string]: unknown;
    };
    /**
     * Followers average rating of the movie
     */
    follower_avg_rating?: {
        [key: string]: unknown;
    };
};

export type PaginationMetaDto = {
    total_results: number;
    total_pages: number;
    current_page: number;
    per_page: number;
};

export type SearchMoviesResponseDto = {
    data: Array<MovieDto>;
    pagination: PaginationMetaDto;
};

export type TvSeriesDto = {
    /**
     * The TV series' unique identifier
     */
    id: number;
    /**
     * The name of the TV series
     */
    name: {
        [key: string]: unknown;
    };
    /**
     * Poster path of the TV series
     */
    poster_path?: {
        [key: string]: unknown;
    };
    /**
     * Poster URL of the TV series
     */
    poster_url?: {
        [key: string]: unknown;
    };
    /**
     * Backdrop path of the TV series
     */
    backdrop_path: {
        [key: string]: unknown;
    };
    /**
     * Backdrop URL of the TV series
     */
    backdrop_url?: {
        [key: string]: unknown;
    };
    /**
     * Creators of the TV series
     */
    created_by: Array<PersonDto>;
    /**
     * Genres of the TV series
     */
    genres: Array<GenreDto>;
    /**
     * First air date of the TV series
     */
    first_air_date: {
        [key: string]: unknown;
    };
    /**
     * Last air date of the TV series
     */
    last_air_date: {
        [key: string]: unknown;
    };
    /**
     * Overview of the TV series
     */
    overview: {
        [key: string]: unknown;
    };
    /**
     * Number of seasons in the TV series
     */
    number_of_seasons: {
        [key: string]: unknown;
    };
    /**
     * Number of episodes in the TV series
     */
    number_of_episodes: {
        [key: string]: unknown;
    };
    /**
     * Is it in production?
     */
    in_production: boolean;
    /**
     * Original language of the TV series
     */
    original_language: {
        [key: string]: unknown;
    };
    /**
     * Original name of the TV series
     */
    original_name: {
        [key: string]: unknown;
    };
    /**
     * Status of the TV series
     */
    status: {
        [key: string]: unknown;
    };
    /**
     * Type of the TV series
     */
    type: {
        [key: string]: unknown;
    };
    /**
     * Popularity score of the TV series
     */
    popularity: number;
    /**
     * Vote average of the TV series
     */
    vote_average: number;
    /**
     * Vote count of the TV series
     */
    vote_count: number;
    /**
     * Slug of the TV series
     */
    slug?: {
        [key: string]: unknown;
    };
    /**
     * URL to the TV series page
     */
    url?: {
        [key: string]: unknown;
    };
    /**
     * Followers average rating of the TV series
     */
    follower_avg_rating?: {
        [key: string]: unknown;
    };
};

export type SearchTvSeriesResponseDto = {
    data: Array<TvSeriesDto>;
    pagination: PaginationMetaDto;
};

export type SearchPersonsResponseDto = {
    data: Array<PersonDto>;
    pagination: PaginationMetaDto;
};

export type ProfileDto = {
    /**
     * The user's unique identifier
     */
    id: string;
    /**
     * The user's username
     */
    username: string;
    /**
     * The user's full name
     */
    full_name: string;
    /**
     * The user's biography
     */
    bio?: {
        [key: string]: unknown;
    };
    /**
     * URL to the user's avatar
     */
    avatar_url?: {
        [key: string]: unknown;
    };
    /**
     * URL to the user's website
     */
    website?: {
        [key: string]: unknown;
    };
    /**
     * The user's favorite color
     */
    favorite_color?: {
        [key: string]: unknown;
    };
    /**
     * The number of followers
     */
    followers_count: number;
    /**
     * The number of users this user is following
     */
    following_count: number;
    /**
     * URL to the user's background image
     */
    background_url?: {
        [key: string]: unknown;
    };
    /**
     * Indicates if the user has a premium account
     */
    premium: boolean;
    /**
     * Indicates if the user profile is private
     */
    private: boolean;
    /**
     * Indicates if the user profile is visible
     */
    visible: boolean;
    /**
     * The timestamp of when the user was created
     */
    created_at: string;
};

export type PlaylistDto = {
    /**
     * The unique identifier of the playlist
     */
    id: number;
    /**
     * The timestamp of when the playlist was created
     */
    created_at: string;
    /**
     * The timestamp of when the playlist was last updated
     */
    updated_at?: {
        [key: string]: unknown;
    };
    /**
     * The ID of the user who owns the playlist
     */
    user_id: string;
    /**
     * The title of the playlist
     */
    title: string;
    /**
     * The description of the playlist
     */
    description?: {
        [key: string]: unknown;
    };
    /**
     * URL to the playlist poster image
     */
    poster_url?: {
        [key: string]: unknown;
    };
    /**
     * Indicates if the playlist is private
     */
    private: boolean;
    /**
     * The number of items in the playlist
     */
    items_count: number;
    /**
     * The number of times the playlist has been saved
     */
    saved_count: number;
    /**
     * The number of likes the playlist has received
     */
    likes_count: number;
    /**
     * The type of the playlist
     */
    type: 'movie' | 'tv_series';
    /**
     * The user object
     */
    user: ProfileDto;
};

export type SearchPlaylistsResponseDto = {
    data: Array<PlaylistDto>;
    pagination: PaginationMetaDto;
};

export type SearchUsersResponseDto = {
    data: Array<ProfileDto>;
    pagination: PaginationMetaDto;
};

export type BestResultItem = {
    /**
     * The type of the best result item
     */
    type: 'movie' | 'tv_series' | 'person' | 'user' | 'playlist';
    /**
     * The data for the best result item. The actual schema depends on the `type` field.
     */
    data: MovieDto | TvSeriesDto | PersonDto | ProfileDto | PlaylistDto;
};

export type BestResultSearchResponseDto = {
    /**
     * The single best result found across all types, based on a hybrid score of text match and popularity.
     */
    bestResult?: BestResultItem;
    /**
     * Paginated movie search results
     */
    movies: SearchMoviesResponseDto;
    /**
     * Paginated TV series search results
     */
    tv_series: SearchTvSeriesResponseDto;
    /**
     * Paginated person search results
     */
    persons: SearchPersonsResponseDto;
    /**
     * Paginated user search results
     */
    users: SearchUsersResponseDto;
    /**
     * Paginated playlist search results
     */
    playlists: SearchPlaylistsResponseDto;
};

export type HealthControllerGetHelloData = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query?: never;
    url: '/';
};

export type HealthControllerGetHelloResponses = {
    200: unknown;
};

export type HealthControllerGetHealthData = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthControllerGetHealthResponses = {
    200: unknown;
};

export type MoviesSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field for movies
         */
        sort_by?: 'popularity' | 'release_date' | 'vote_average';
        /**
         * Comma-separated list of genre IDs to filter by
         */
        genre_ids?: string;
        /**
         * Minimum runtime in minutes
         */
        runtime_min?: number;
        /**
         * Maximum runtime in minutes
         */
        runtime_max?: number;
        /**
         * Minimum release date (YYYY-MM-DD)
         */
        release_date_min?: string;
        /**
         * Maximum release date (YYYY-MM-DD)
         */
        release_date_max?: string;
    };
    url: '/v1/search/movies';
};

export type MoviesSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type MoviesSearchControllerSearchV1Responses = {
    /**
     * Movies found successfully
     */
    200: SearchMoviesResponseDto;
};

export type MoviesSearchControllerSearchV1Response = MoviesSearchControllerSearchV1Responses[keyof MoviesSearchControllerSearchV1Responses];

export type TvSeriesSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field for TV series
         */
        sort_by?: 'popularity' | 'first_air_date' | 'vote_average';
        /**
         * Comma-separated list of genre IDs to filter by
         */
        genre_ids?: string;
        /**
         * Minimum number of seasons
         */
        number_of_seasons_min?: number;
        /**
         * Maximum number of seasons
         */
        number_of_seasons_max?: number;
        /**
         * Minimum number of episodes
         */
        number_of_episodes_min?: number;
        /**
         * Maximum number of episodes
         */
        number_of_episodes_max?: number;
        /**
         * Minimum vote average (0-10)
         */
        vote_average_min?: number;
        /**
         * Maximum vote average (0-10)
         */
        vote_average_max?: number;
        /**
         * Minimum first air date (YYYY-MM-DD)
         */
        first_air_date_min?: string;
        /**
         * Maximum first air date (YYYY-MM-DD)
         */
        first_air_date_max?: string;
    };
    url: '/v1/search/tv-series';
};

export type TvSeriesSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type TvSeriesSearchControllerSearchV1Responses = {
    /**
     * TV series found successfully
     */
    200: SearchTvSeriesResponseDto;
};

export type TvSeriesSearchControllerSearchV1Response = TvSeriesSearchControllerSearchV1Responses[keyof TvSeriesSearchControllerSearchV1Responses];

export type PersonsSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field for persons
         */
        sort_by?: 'popularity';
    };
    url: '/v1/search/persons';
};

export type PersonsSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type PersonsSearchControllerSearchV1Responses = {
    /**
     * Persons found successfully
     */
    200: SearchPersonsResponseDto;
};

export type PersonsSearchControllerSearchV1Response = PersonsSearchControllerSearchV1Responses[keyof PersonsSearchControllerSearchV1Responses];

export type PlaylistsSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field
         */
        sort_by?: 'created_at' | 'updated_at' | 'title';
    };
    url: '/v1/search/playlists';
};

export type PlaylistsSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type PlaylistsSearchControllerSearchV1Responses = {
    /**
     * Playlists found successfully
     */
    200: SearchPlaylistsResponseDto;
};

export type PlaylistsSearchControllerSearchV1Response = PlaylistsSearchControllerSearchV1Responses[keyof PlaylistsSearchControllerSearchV1Responses];

export type UsersSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Comma-separated list of user IDs to exclude from the search
         */
        exclude_ids?: string;
    };
    url: '/v1/search/users';
};

export type UsersSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type UsersSearchControllerSearchV1Responses = {
    /**
     * Users found successfully
     */
    200: SearchUsersResponseDto;
};

export type UsersSearchControllerSearchV1Response = UsersSearchControllerSearchV1Responses[keyof UsersSearchControllerSearchV1Responses];

export type BestResultSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * The number of results to return per type (movie, TV series, etc.).
         */
        results_per_type?: number;
    };
    url: '/v1/search/best-result';
};

export type BestResultSearchControllerSearchV1Responses = {
    /**
     * Best results found successfully
     */
    200: BestResultSearchResponseDto;
};

export type BestResultSearchControllerSearchV1Response = BestResultSearchControllerSearchV1Responses[keyof BestResultSearchControllerSearchV1Responses];
