// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { BestResultSearchControllerSearchV1Data, BestResultSearchControllerSearchV1Responses, HealthControllerGetHealthData, HealthControllerGetHealthResponses, HealthControllerGetHelloData, HealthControllerGetHelloResponses, MovieReviewsControllerUpsertMovieReviewV1Data, MovieReviewsControllerUpsertMovieReviewV1Errors, MovieReviewsControllerUpsertMovieReviewV1Responses, MoviesSearchControllerSearchV1Data, MoviesSearchControllerSearchV1Errors, MoviesSearchControllerSearchV1Responses, PersonsSearchControllerSearchV1Data, PersonsSearchControllerSearchV1Errors, PersonsSearchControllerSearchV1Responses, PlaylistsSearchControllerSearchV1Data, PlaylistsSearchControllerSearchV1Errors, PlaylistsSearchControllerSearchV1Responses, TvSeriesReviewsControllerUpsertTvSeriesReviewV1Data, TvSeriesReviewsControllerUpsertTvSeriesReviewV1Errors, TvSeriesReviewsControllerUpsertTvSeriesReviewV1Responses, TvSeriesSearchControllerSearchV1Data, TvSeriesSearchControllerSearchV1Errors, TvSeriesSearchControllerSearchV1Responses, UsersSearchControllerSearchV1Data, UsersSearchControllerSearchV1Errors, UsersSearchControllerSearchV1Responses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const healthControllerGetHello = <ThrowOnError extends boolean = false>(options?: Options<HealthControllerGetHelloData, ThrowOnError>) => (options?.client ?? client).get<HealthControllerGetHelloResponses, unknown, ThrowOnError>({ url: '/', ...options });

export const healthControllerGetHealth = <ThrowOnError extends boolean = false>(options?: Options<HealthControllerGetHealthData, ThrowOnError>) => (options?.client ?? client).get<HealthControllerGetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Search movies
 *
 * Search for movies using full-text search and advanced filtering.
 */
export const moviesSearchControllerSearchV1 = <ThrowOnError extends boolean = false>(options: Options<MoviesSearchControllerSearchV1Data, ThrowOnError>) => (options.client ?? client).get<MoviesSearchControllerSearchV1Responses, MoviesSearchControllerSearchV1Errors, ThrowOnError>({ url: '/v1/search/movies', ...options });

/**
 * Search TV series
 *
 * Search for TV series using full-text search and advanced filtering.
 */
export const tvSeriesSearchControllerSearchV1 = <ThrowOnError extends boolean = false>(options: Options<TvSeriesSearchControllerSearchV1Data, ThrowOnError>) => (options.client ?? client).get<TvSeriesSearchControllerSearchV1Responses, TvSeriesSearchControllerSearchV1Errors, ThrowOnError>({ url: '/v1/search/tv-series', ...options });

/**
 * Search persons
 *
 * Search for persons (actors, directors, etc.) using full-text search.
 */
export const personsSearchControllerSearchV1 = <ThrowOnError extends boolean = false>(options: Options<PersonsSearchControllerSearchV1Data, ThrowOnError>) => (options.client ?? client).get<PersonsSearchControllerSearchV1Responses, PersonsSearchControllerSearchV1Errors, ThrowOnError>({ url: '/v1/search/persons', ...options });

/**
 * Search playlists
 *
 * Search for playlists using full-text search. Returns public playlists or user-owned playlists if authenticated.
 */
export const playlistsSearchControllerSearchV1 = <ThrowOnError extends boolean = false>(options: Options<PlaylistsSearchControllerSearchV1Data, ThrowOnError>) => (options.client ?? client).get<PlaylistsSearchControllerSearchV1Responses, PlaylistsSearchControllerSearchV1Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/search/playlists',
    ...options
});

/**
 * Search users
 *
 * Search for users using full-text search.
 */
export const usersSearchControllerSearchV1 = <ThrowOnError extends boolean = false>(options: Options<UsersSearchControllerSearchV1Data, ThrowOnError>) => (options.client ?? client).get<UsersSearchControllerSearchV1Responses, UsersSearchControllerSearchV1Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/search/users',
    ...options
});

/**
 * Search for the best result across all types
 *
 * Returns the top search results for movies, TV series, people, playlists, and users.
 */
export const bestResultSearchControllerSearchV1 = <ThrowOnError extends boolean = false>(options: Options<BestResultSearchControllerSearchV1Data, ThrowOnError>) => (options.client ?? client).get<BestResultSearchControllerSearchV1Responses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/search/best-result',
    ...options
});

/**
 * Create or update a movie review
 */
export const movieReviewsControllerUpsertMovieReviewV1 = <ThrowOnError extends boolean = false>(options: Options<MovieReviewsControllerUpsertMovieReviewV1Data, ThrowOnError>) => (options.client ?? client).put<MovieReviewsControllerUpsertMovieReviewV1Responses, MovieReviewsControllerUpsertMovieReviewV1Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/movie/{movieId}/review',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create or update a TV series review
 */
export const tvSeriesReviewsControllerUpsertTvSeriesReviewV1 = <ThrowOnError extends boolean = false>(options: Options<TvSeriesReviewsControllerUpsertTvSeriesReviewV1Data, ThrowOnError>) => (options.client ?? client).put<TvSeriesReviewsControllerUpsertTvSeriesReviewV1Responses, TvSeriesReviewsControllerUpsertTvSeriesReviewV1Errors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/v1/tv/{tvSeriesId}/review',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
