// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type Person = {
    /**
     * The person's unique identifier
     */
    id: number;
    /**
     * The person's name
     */
    name: string | null;
    /**
     * The person's profile image path
     */
    profile_path: string | null;
    /**
     * The person's profile image URL
     */
    profile_url: string | null;
    /**
     * The person's birthday
     */
    birthday: string | null;
    /**
     * The person's deathday
     */
    deathday: string | null;
    /**
     * The person's homepage URL
     */
    homepage: string | null;
    /**
     * The person's imdb identifier
     */
    imdb_id: string | null;
    /**
     * The person's kown for department
     */
    known_for_department: string | null;
    /**
     * The person's place of birth
     */
    place_of_birth: string | null;
    /**
     * The person's gender: 0 = Not specified, 1 = Female, 2 = Male, 3 = Non-binary
     */
    gender: number | null;
    /**
     * The person's biography
     */
    biography: string | null;
    /**
     * The person's popularity score
     */
    popularity: number | null;
    /**
     * The person's slug
     */
    slug: string | null;
    /**
     * The person's URL
     */
    url: string | null;
};

export type Genre = {
    /**
     * The genre's ID
     */
    id: number;
    /**
     * The name of the genre
     */
    name: string;
};

export type Movie = {
    /**
     * The movie's unique identifier
     */
    id: number;
    /**
     * The title of the movie
     */
    title: string | null;
    /**
     * Poster path of the movie
     */
    poster_path: string | null;
    /**
     * Poster URL of the movie
     */
    poster_url: string | null;
    /**
     * Backdrop path of the movie
     */
    backdrop_path: string | null;
    /**
     * Backdrop URL of the movie
     */
    backdrop_url: string | null;
    /**
     * Directors of the movie
     */
    directors: Array<Person>;
    /**
     * Genres of the movie
     */
    genres: Array<Genre>;
    /**
     * Release date of the movie
     */
    release_date: string | null;
    /**
     * Overview of the movie
     */
    overview: string | null;
    /**
     * Budget of the movie in USD
     */
    budget: number | null;
    /**
     * Homepage URL of the movie
     */
    homepage: string | null;
    /**
     * Revenue of the movie in USD
     */
    revenue: number | null;
    /**
     * Runtime of the movie in minutes
     */
    runtime: number | null;
    /**
     * Original language of the movie
     */
    original_language: string | null;
    /**
     * Original title of the movie
     */
    original_title: string | null;
    /**
     * Status of the movie
     */
    status: string | null;
    /**
     * Popularity score of the movie
     */
    popularity: number;
    /**
     * Vote average of the movie
     */
    vote_average: number;
    /**
     * Vote count of the movie
     */
    vote_count: number;
    /**
     * Slug of the movie
     */
    slug: string | null;
    /**
     * URL to the movie page
     */
    url: string | null;
    /**
     * Followers average rating of the movie
     */
    follower_avg_rating: number | null;
};

export type PaginationMeta = {
    total_results: number;
    total_pages: number;
    current_page: number;
    per_page: number;
};

export type SearchMoviesResponse = {
    data: Array<Movie>;
    pagination: PaginationMeta;
};

export type TvSeries = {
    /**
     * The TV series' unique identifier
     */
    id: number;
    /**
     * The name of the TV series
     */
    name: string | null;
    /**
     * Poster path of the TV series
     */
    poster_path: string | null;
    /**
     * Poster URL of the TV series
     */
    poster_url: string | null;
    /**
     * Backdrop path of the TV series
     */
    backdrop_path: string | null;
    /**
     * Backdrop URL of the TV series
     */
    backdrop_url: string | null;
    /**
     * Creators of the TV series
     */
    created_by: Array<Person>;
    /**
     * Genres of the TV series
     */
    genres: Array<Genre>;
    /**
     * First air date of the TV series
     */
    first_air_date: string | null;
    /**
     * Last air date of the TV series
     */
    last_air_date: string | null;
    /**
     * Overview of the TV series
     */
    overview: string | null;
    /**
     * Number of seasons in the TV series
     */
    number_of_seasons: number | null;
    /**
     * Number of episodes in the TV series
     */
    number_of_episodes: number | null;
    /**
     * Is it in production?
     */
    in_production: boolean;
    /**
     * Original language of the TV series
     */
    original_language: string | null;
    /**
     * Original name of the TV series
     */
    original_name: string | null;
    /**
     * Status of the TV series
     */
    status: string | null;
    /**
     * Type of the TV series
     */
    type: string | null;
    /**
     * Popularity score of the TV series
     */
    popularity: number;
    /**
     * Vote average of the TV series
     */
    vote_average: number;
    /**
     * Vote count of the TV series
     */
    vote_count: number;
    /**
     * Slug of the TV series
     */
    slug: string | null;
    /**
     * URL to the TV series page
     */
    url: string | null;
    /**
     * Followers average rating of the TV series
     */
    follower_avg_rating: number | null;
};

export type SearchTvSeriesResponse = {
    data: Array<TvSeries>;
    pagination: PaginationMeta;
};

export type SearchPersonsResponse = {
    data: Array<Person>;
    pagination: PaginationMeta;
};

export type Profile = {
    /**
     * The user's unique identifier
     */
    id: string;
    /**
     * The user's username
     */
    username: string;
    /**
     * The user's full name
     */
    full_name: string;
    /**
     * The user's biography
     */
    bio: string | null;
    /**
     * URL to the user's avatar
     */
    avatar_url: string | null;
    /**
     * URL to the user's website
     */
    website: string | null;
    /**
     * The user's favorite color
     */
    favorite_color: string | null;
    /**
     * The number of followers
     */
    followers_count: number;
    /**
     * The number of users this user is following
     */
    following_count: number;
    /**
     * URL to the user's background image
     */
    background_url: string | null;
    /**
     * Indicates if the user has a premium account
     */
    premium: boolean;
    /**
     * Indicates if the user profile is private
     */
    private: boolean;
    /**
     * Indicates if the user profile is visible
     */
    visible: boolean;
    /**
     * The timestamp of when the user was created
     */
    created_at: string;
};

export type Playlist = {
    /**
     * The unique identifier of the playlist
     */
    id: number;
    /**
     * The timestamp of when the playlist was created
     */
    created_at: string;
    /**
     * The timestamp of when the playlist was last updated
     */
    updated_at: string | null;
    /**
     * The ID of the user who owns the playlist
     */
    user_id: string;
    /**
     * The title of the playlist
     */
    title: string;
    /**
     * The description of the playlist
     */
    description: string | null;
    /**
     * URL to the playlist poster image
     */
    poster_url: string | null;
    /**
     * Indicates if the playlist is private
     */
    private: boolean;
    /**
     * The number of items in the playlist
     */
    items_count: number;
    /**
     * The number of times the playlist has been saved
     */
    saved_count: number;
    /**
     * The number of likes the playlist has received
     */
    likes_count: number;
    /**
     * The type of the playlist
     */
    type: 'movie' | 'tv_series';
    /**
     * The user object
     */
    user: Profile;
};

export type SearchPlaylistsResponse = {
    data: Array<Playlist>;
    pagination: PaginationMeta;
};

export type SearchUsersResponse = {
    data: Array<Profile>;
    pagination: PaginationMeta;
};

export type BestResultItem = {
    /**
     * The type of the best result item
     */
    type: 'movie' | 'tv_series' | 'person' | 'user' | 'playlist';
    /**
     * The data for the best result item. The actual schema depends on the `type` field.
     */
    data: Movie | TvSeries | Person | Profile | Playlist;
};

export type SearchBestResultResponse = {
    /**
     * The single best result found across all types, based on a hybrid score of text match and popularity.
     */
    bestResult?: BestResultItem;
    /**
     * Paginated movie search results
     */
    movies: SearchMoviesResponse;
    /**
     * Paginated TV series search results
     */
    tv_series: SearchTvSeriesResponse;
    /**
     * Paginated person search results
     */
    persons: SearchPersonsResponse;
    /**
     * Paginated user search results
     */
    users: SearchUsersResponse;
    /**
     * Paginated playlist search results
     */
    playlists: SearchPlaylistsResponse;
};

export type CreateReviewDto = {
    /**
     * The title of the review
     */
    title?: string | null;
    /**
     * The body of the review, in HTML format
     */
    body: string;
};

export type ReviewMovieDto = {
    /**
     * The unique identifier for the movie review (same as user_activity_movie_id).
     */
    id: number;
    /**
     * Timestamp when the review was created.
     */
    created_at: string;
    /**
     * Timestamp when the review was last updated.
     */
    updated_at: string;
    /**
     * Optional title of the review (max 50 characters).
     */
    title: string | null;
    /**
     * Number of times the review has been viewed.
     */
    views_count: number;
    /**
     * Number of likes the review has received.
     */
    likes_count: number;
    /**
     * Number of comments on the review.
     */
    comments_count: number;
    /**
     * The main body of the review (can contain HTML).
     */
    body: string;
};

export type ReviewTvSeriesDto = {
    /**
     * The unique identifier for the TV series review (same as user_activity_tv_series_id).
     */
    id: number;
    /**
     * Timestamp when the review was created.
     */
    created_at: string;
    /**
     * Timestamp when the review was last updated.
     */
    updated_at: string;
    /**
     * Optional title of the review (max 50 characters).
     */
    title: string | null;
    /**
     * Number of times the review has been viewed.
     */
    views_count: number;
    /**
     * Number of likes the review has received.
     */
    likes_count: number;
    /**
     * Number of comments on the review.
     */
    comments_count: number;
    /**
     * The main body of the review (can contain HTML).
     */
    body: string;
};

export type HealthControllerGetHelloData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type HealthControllerGetHelloResponses = {
    200: unknown;
};

export type HealthControllerGetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthControllerGetHealthResponses = {
    200: unknown;
};

export type MoviesSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field for movies
         */
        sort_by?: 'popularity' | 'release_date' | 'vote_average';
        /**
         * Comma-separated list of genre IDs to filter by
         */
        genre_ids?: string;
        /**
         * Minimum runtime in minutes
         */
        runtime_min?: number;
        /**
         * Maximum runtime in minutes
         */
        runtime_max?: number;
        /**
         * Minimum release date (YYYY-MM-DD)
         */
        release_date_min?: string;
        /**
         * Maximum release date (YYYY-MM-DD)
         */
        release_date_max?: string;
    };
    url: '/v1/search/movies';
};

export type MoviesSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type MoviesSearchControllerSearchV1Responses = {
    /**
     * Movies found successfully
     */
    200: SearchMoviesResponse;
};

export type MoviesSearchControllerSearchV1Response = MoviesSearchControllerSearchV1Responses[keyof MoviesSearchControllerSearchV1Responses];

export type TvSeriesSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field for TV series
         */
        sort_by?: 'popularity' | 'first_air_date' | 'vote_average';
        /**
         * Comma-separated list of genre IDs to filter by
         */
        genre_ids?: string;
        /**
         * Minimum number of seasons
         */
        number_of_seasons_min?: number;
        /**
         * Maximum number of seasons
         */
        number_of_seasons_max?: number;
        /**
         * Minimum number of episodes
         */
        number_of_episodes_min?: number;
        /**
         * Maximum number of episodes
         */
        number_of_episodes_max?: number;
        /**
         * Minimum vote average (0-10)
         */
        vote_average_min?: number;
        /**
         * Maximum vote average (0-10)
         */
        vote_average_max?: number;
        /**
         * Minimum first air date (YYYY-MM-DD)
         */
        first_air_date_min?: string;
        /**
         * Maximum first air date (YYYY-MM-DD)
         */
        first_air_date_max?: string;
    };
    url: '/v1/search/tv-series';
};

export type TvSeriesSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type TvSeriesSearchControllerSearchV1Responses = {
    /**
     * TV series found successfully
     */
    200: SearchTvSeriesResponse;
};

export type TvSeriesSearchControllerSearchV1Response = TvSeriesSearchControllerSearchV1Responses[keyof TvSeriesSearchControllerSearchV1Responses];

export type PersonsSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field for persons
         */
        sort_by?: 'popularity';
    };
    url: '/v1/search/persons';
};

export type PersonsSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type PersonsSearchControllerSearchV1Responses = {
    /**
     * Persons found successfully
     */
    200: SearchPersonsResponse;
};

export type PersonsSearchControllerSearchV1Response = PersonsSearchControllerSearchV1Responses[keyof PersonsSearchControllerSearchV1Responses];

export type PlaylistsSearchControllerSearchV1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Sort field
         */
        sort_by?: 'created_at' | 'updated_at' | 'title';
    };
    url: '/v1/search/playlists';
};

export type PlaylistsSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type PlaylistsSearchControllerSearchV1Responses = {
    /**
     * Playlists found successfully
     */
    200: SearchPlaylistsResponse;
};

export type PlaylistsSearchControllerSearchV1Response = PlaylistsSearchControllerSearchV1Responses[keyof PlaylistsSearchControllerSearchV1Responses];

export type UsersSearchControllerSearchV1Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * Comma-separated list of user IDs to exclude from the search
         */
        exclude_ids?: string;
    };
    url: '/v1/search/users';
};

export type UsersSearchControllerSearchV1Errors = {
    /**
     * Invalid query parameters
     */
    400: unknown;
};

export type UsersSearchControllerSearchV1Responses = {
    /**
     * Users found successfully
     */
    200: SearchUsersResponse;
};

export type UsersSearchControllerSearchV1Response = UsersSearchControllerSearchV1Responses[keyof UsersSearchControllerSearchV1Responses];

export type BestResultSearchControllerSearchV1Data = {
    body?: never;
    headers?: {
        /**
         * The language for the response. Defaults to "en-US".
         */
        language?: string;
    };
    path?: never;
    query: {
        /**
         * Page number
         */
        page?: number;
        /**
         * Number of results per page
         */
        per_page?: number;
        /**
         * Search query string
         */
        q: string;
        /**
         * The number of results to return per type (movie, TV series, etc.).
         */
        results_per_type?: number;
    };
    url: '/v1/search/best-result';
};

export type BestResultSearchControllerSearchV1Responses = {
    /**
     * Best results found successfully
     */
    200: SearchBestResultResponse;
};

export type BestResultSearchControllerSearchV1Response = BestResultSearchControllerSearchV1Responses[keyof BestResultSearchControllerSearchV1Responses];

export type MovieReviewsControllerUpsertMovieReviewV1Data = {
    body: CreateReviewDto;
    path: {
        movieId: number;
    };
    query?: never;
    url: '/v1/movie/{movieId}/review';
};

export type MovieReviewsControllerUpsertMovieReviewV1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type MovieReviewsControllerUpsertMovieReviewV1Responses = {
    /**
     * Review created or updated successfully
     */
    200: ReviewMovieDto;
};

export type MovieReviewsControllerUpsertMovieReviewV1Response = MovieReviewsControllerUpsertMovieReviewV1Responses[keyof MovieReviewsControllerUpsertMovieReviewV1Responses];

export type TvSeriesReviewsControllerUpsertTvSeriesReviewV1Data = {
    body: CreateReviewDto;
    path: {
        tvSeriesId: number;
    };
    query?: never;
    url: '/v1/tv/{tvSeriesId}/review';
};

export type TvSeriesReviewsControllerUpsertTvSeriesReviewV1Errors = {
    /**
     * Unauthorized
     */
    401: unknown;
};

export type TvSeriesReviewsControllerUpsertTvSeriesReviewV1Responses = {
    /**
     * Review created or updated successfully
     */
    200: ReviewTvSeriesDto;
};

export type TvSeriesReviewsControllerUpsertTvSeriesReviewV1Response = TvSeriesReviewsControllerUpsertTvSeriesReviewV1Responses[keyof TvSeriesReviewsControllerUpsertTvSeriesReviewV1Responses];
